background {
    monitor =
    path = /home/marcman/wallpapers/curvy_linux.jpg
    color = rgba(25, 20, 20, 1.0)

    # all these options are taken from hyprland, see https://wiki.hyprland.org/Configuring/Variables/#blur for explanations
    blur_passes = 0 # 0 disables blurring
    blur_size = 7
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

#image {
#    monitor =
#    path = ~/Pictures/back_cropped.jpg
#    size = 250 # lesser side if not 1:1 ratio
#    rounding = -1 # negative values mean circle
#    border_size = 4
#    border_color = rgb(221, 221, 221)
#    rotate = 0 # degrees, counter-clockwise
#    reload_time = -1 # seconds between reloading, 0 to reload with SIGUSR2
#    reload_cmd =  # command to get new path. if empty, old path will be used. don't run "follow" commands like tail -F
#
#    position = 0, 100
#    halign = center
#    valign = center
#}

label {
    monitor =
    text = $FAIL
    text_align = center # center/right or any value for default left. multi-line text alignment inside label container
    color = rgba(255, 255, 255, 1.0)
    font_size = 15
    font_family = Noto Sans
    rotate = 0 # degrees, counter-clockwise

    position = 0, -100
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    text_align = center # center/right or any value for default left. multi-line text alignment inside label container
    color = rgba(255, 255, 255, 1.0)
    font_size = 35
    font_family = Noto Sans
    rotate = 0 # degrees, counter-clockwise

    position = -500, 300
    halign = center
    valign = center
}
